language: node_js
sudo: false
node_js: [22, 20]
before_install:
  - corepack enable
install:
  - travis_retry pnpm install --frozen-lockfile
before_script:
  - echo ':)'
script: pnpm test
matrix:
  include:
    - name: '👕Linter'
      node_js: 22
      before_script: skip
      script: pnpm lint
    - name: 'Build check'
      node_js: 22
      before_script: skip
      script: pnpm build
notifications:
  email: false
